<?php
// Generated by WFWorkflow

if (file_exists('custom/include/Workflow/WFManager.php')) {
    require_once 'custom/include/Workflow/WFManager.php';
    $app_list_strings['Opportunities_sales_stage_wf_options'] =
        WFManager::getAllStatuses(BeanFactory::newBean('Opportunities'));
}
