<?php
// Generated by WFWorkflow

/**
 * Status field settings
 */
$dictionary['Opportunity']['fields']['sales_stage']['function'] = 'wf_getNewStatuses';
$dictionary['Opportunity']['fields']['sales_stage']['default'] = '';
$dictionary['Opportunity']['fields']['sales_stage']['required'] = false;
$dictionary['Opportunity']['fields']['sales_stage']['options'] = 'Opportunities_sales_stage_wf_options';
